server:
  port: 8085

spring:
  profiles:
    active: local
  mongodb:
    embedded:
      version: 4.0.21
---
spring:
  config:
    activate:
      on-profile: local
  data:
    mongodb:
      host: localhost
      port: 27017
      database: movies_ms
---
spring:
  config:
    activate:
      on-profile: nonprod
  data:
    mongodb:
      host: localhost
      port: 27017
      database: movies_ms
---
spring:
  config:
    activate:
      on-profile: prod
  data:
    mongodb:
      host: localhost
      port: 27017
      database: movies_ms
---
logging:
  level:
    root: info